---
kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/sh", "-c"]
        args: ["echo 'Hello, linkerd!' > /usr/share/nginx/html/index.html && nginx -g \"daemon off;\""]
        ports:
        - name: service
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: service
    port: 80
    targetPort: 80
