---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  replicas: 3
  selector:
    app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/helloworld:0.1.6
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/sh"
        - "-c"
        - "http_proxy=`hostIP.sh`:4140 helloworld -addr=:7779 -text=api -target=hello -json"
        ports:
        - name: service
          containerPort: 7779
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - proxy
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - name: http
    port: 7779
