---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: l5d-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's 
    name: default
    # Reference to upper's 
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
